### ISSUE TITLE
(Parent Issue) As a developer, I want to update the code base to support the new versions of pyglet functions, so the program (main.py) will run on Pyglet 2.0

### ISSUE THREAD

**Issue by JosephBehr** [WSUCEG-7140/TeamK-MinecraftPython#5]
Child issues include: 3,4,5 

Definition of Done:
- When running main.py file, no pyglet errors appear.

**Comment by josephreddyyeruva** [comment]
I did not understand bro.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JosephBehr** [comment]
Closed the parent issue since we have it broken out into 3 separate issues that are assigned to each of us. I think you are assigned to the pyglet.batch issue, either issue 4 or 5
