### ISSUE TITLE
As a developer, I want to include the most recent version of Pyglet.gl (GL_Fog) in order to get the program to run on pyglet 2.0

### ISSUE THREAD

**Issue by JosephBehr** [WSUCEG-7140/TeamK-MinecraftPython#6]
Definition of done:
- Attribute error "GL_Fog not defined" no longer appears when trying to run main.py.
- Suitable replacement within Pyglet 2.0 found OR GL_Fog determined unnecessary. [GL_Fog Functionality](https://docs.gl/gl3/glFog)

- Test setup_fog function is able to run

**Comment by josephreddyyeruva** [comment]
I've carefully reviewed the changes you've made. Overall, I find the addition of GL_Fog promising.
